import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import guestRouter from "./guest";
import usersRouter from "./users";
import rolesRouter from "./roles";
import pagesRouter from "./pages";
import entitiesRouter from "./entities";
import fieldsRouter from "./fields";
import pageFieldsRouter from "./page-fields";
import statusesRouter from "./statuses";
import transitionsRouter from "./transitions";
import automationsRouter from "./automations";
import customFiltersRouter from "./custom-filters";
import recordsRouter from "./records";
import relationsRouter from "./relations";
import viewsRouter from "./views";
import translationsRouter from "./translations";
import dashboardRouter from "./dashboard";
import auditLogRouter from "./audit-log";
import eventsRouter from "./events";
import modulesRouter from "./modules";
import columnGroupsRouter from "./column-groups";
import storageRouter from "./storage";
import googleDriveRouter from "./google-drive";
import settingsRouter from "./settings";
import deletedFilesRouter from "./deleted-files";
import localFoldersRouter from "./local-folders";
import importRouter from "./import";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(guestRouter);
router.use(usersRouter);
router.use(rolesRouter);
router.use(pagesRouter);
router.use(entitiesRouter);
router.use(fieldsRouter);
router.use(pageFieldsRouter);
router.use(statusesRouter);
router.use(transitionsRouter);
router.use(automationsRouter);
router.use(customFiltersRouter);
router.use(recordsRouter);
router.use(relationsRouter);
router.use(viewsRouter);
router.use(translationsRouter);
router.use(dashboardRouter);
router.use(auditLogRouter);
router.use(eventsRouter);
router.use(modulesRouter);
router.use(columnGroupsRouter);
router.use(storageRouter);
router.use(googleDriveRouter);
router.use(settingsRouter);
router.use(deletedFilesRouter);
router.use(localFoldersRouter);
router.use(importRouter);

export default router;
