-- Idempotent schema sync (generated from dev schema, 2026-08-10).
-- Safe to run multiple times: only ADDS missing tables/columns/sequences/constraints/indexes.
BEGIN;
CREATE TABLE IF NOT EXISTS app_settings ();
CREATE TABLE IF NOT EXISTS audit_log ();
CREATE TABLE IF NOT EXISTS column_groups ();
CREATE TABLE IF NOT EXISTS custom_filters ();
CREATE TABLE IF NOT EXISTS dashboard_widgets ();
CREATE TABLE IF NOT EXISTS deleted_files ();
CREATE TABLE IF NOT EXISTS entities ();
CREATE TABLE IF NOT EXISTS entity_automation_runs ();
CREATE TABLE IF NOT EXISTS entity_automations ();
CREATE TABLE IF NOT EXISTS entity_fields ();
CREATE TABLE IF NOT EXISTS entity_records ();
CREATE TABLE IF NOT EXISTS entity_statuses ();
CREATE TABLE IF NOT EXISTS entity_transitions ();
CREATE TABLE IF NOT EXISTS google_drive_connection ();
CREATE TABLE IF NOT EXISTS google_drive_folders ();
CREATE TABLE IF NOT EXISTS guest_links ();
CREATE TABLE IF NOT EXISTS local_folders ();
CREATE TABLE IF NOT EXISTS login_history ();
CREATE TABLE IF NOT EXISTS modules ();
CREATE TABLE IF NOT EXISTS page_fields ();
CREATE TABLE IF NOT EXISTS page_record_values ();
CREATE TABLE IF NOT EXISTS pages ();
CREATE TABLE IF NOT EXISTS record_links ();
CREATE TABLE IF NOT EXISTS relations ();
CREATE TABLE IF NOT EXISTS roles ();
CREATE TABLE IF NOT EXISTS system_events ();
CREATE TABLE IF NOT EXISTS translations ();
CREATE TABLE IF NOT EXISTS user_roles ();
CREATE TABLE IF NOT EXISTS users ();
CREATE TABLE IF NOT EXISTS views ();
CREATE SEQUENCE IF NOT EXISTS audit_log_id_seq;
CREATE SEQUENCE IF NOT EXISTS column_groups_id_seq;
CREATE SEQUENCE IF NOT EXISTS custom_filters_id_seq;
CREATE SEQUENCE IF NOT EXISTS dashboard_widgets_id_seq;
CREATE SEQUENCE IF NOT EXISTS deleted_files_id_seq;
CREATE SEQUENCE IF NOT EXISTS entities_id_seq;
CREATE SEQUENCE IF NOT EXISTS entity_automation_runs_id_seq;
CREATE SEQUENCE IF NOT EXISTS entity_automations_id_seq;
CREATE SEQUENCE IF NOT EXISTS entity_fields_id_seq;
CREATE SEQUENCE IF NOT EXISTS entity_records_id_seq;
CREATE SEQUENCE IF NOT EXISTS entity_statuses_id_seq;
CREATE SEQUENCE IF NOT EXISTS entity_transitions_id_seq;
CREATE SEQUENCE IF NOT EXISTS google_drive_connection_id_seq;
CREATE SEQUENCE IF NOT EXISTS google_drive_folders_id_seq;
CREATE SEQUENCE IF NOT EXISTS guest_links_id_seq;
CREATE SEQUENCE IF NOT EXISTS local_folders_id_seq;
CREATE SEQUENCE IF NOT EXISTS login_history_id_seq;
CREATE SEQUENCE IF NOT EXISTS modules_id_seq;
CREATE SEQUENCE IF NOT EXISTS page_fields_id_seq;
CREATE SEQUENCE IF NOT EXISTS page_record_values_id_seq;
CREATE SEQUENCE IF NOT EXISTS pages_id_seq;
CREATE SEQUENCE IF NOT EXISTS record_links_id_seq;
CREATE SEQUENCE IF NOT EXISTS relations_id_seq;
CREATE SEQUENCE IF NOT EXISTS roles_id_seq;
CREATE SEQUENCE IF NOT EXISTS system_events_id_seq;
CREATE SEQUENCE IF NOT EXISTS translations_id_seq;
CREATE SEQUENCE IF NOT EXISTS users_id_seq;
CREATE SEQUENCE IF NOT EXISTS views_id_seq;
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS id integer DEFAULT 1 NOT NULL;
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS app_name_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS subtitle_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS logo_object_path text;
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS currency_symbol text DEFAULT '₽'::text NOT NULL;
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS default_language text DEFAULT 'ru'::text NOT NULL;
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS table_style text DEFAULT 'plain'::text NOT NULL;
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS table_stripe_color text;
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS table_header_color text;
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS table_border_color text;
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS time_zone text DEFAULT 'Asia/Jerusalem'::text NOT NULL;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('audit_log_id_seq'::regclass) NOT NULL;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS entity_id integer;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS record_id integer;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS field_key text;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS old_value text;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS new_value text;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS user_id integer;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE column_groups ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('column_groups_id_seq'::regclass) NOT NULL;
ALTER TABLE column_groups ADD COLUMN IF NOT EXISTS name_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE column_groups ADD COLUMN IF NOT EXISTS color text DEFAULT '#6366f1'::text NOT NULL;
ALTER TABLE column_groups ADD COLUMN IF NOT EXISTS display_mode text DEFAULT 'bar'::text NOT NULL;
ALTER TABLE column_groups ADD COLUMN IF NOT EXISTS text_color text;
ALTER TABLE column_groups ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0 NOT NULL;
ALTER TABLE column_groups ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE column_groups ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE custom_filters ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('custom_filters_id_seq'::regclass) NOT NULL;
ALTER TABLE custom_filters ADD COLUMN IF NOT EXISTS entity_id integer;
ALTER TABLE custom_filters ADD COLUMN IF NOT EXISTS name_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE custom_filters ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true NOT NULL;
ALTER TABLE custom_filters ADD COLUMN IF NOT EXISTS conjunction text DEFAULT 'and'::text NOT NULL;
ALTER TABLE custom_filters ADD COLUMN IF NOT EXISTS groups_json jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE custom_filters ADD COLUMN IF NOT EXISTS inputs_json jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE custom_filters ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0 NOT NULL;
ALTER TABLE custom_filters ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE custom_filters ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE dashboard_widgets ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('dashboard_widgets_id_seq'::regclass) NOT NULL;
ALTER TABLE dashboard_widgets ADD COLUMN IF NOT EXISTS page_id integer;
ALTER TABLE dashboard_widgets ADD COLUMN IF NOT EXISTS title_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE dashboard_widgets ADD COLUMN IF NOT EXISTS config_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE dashboard_widgets ADD COLUMN IF NOT EXISTS visible_role_ids_json jsonb;
ALTER TABLE dashboard_widgets ADD COLUMN IF NOT EXISTS icon text DEFAULT 'bar-chart-3'::text NOT NULL;
ALTER TABLE dashboard_widgets ADD COLUMN IF NOT EXISTS color text DEFAULT 'blue'::text NOT NULL;
ALTER TABLE dashboard_widgets ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0 NOT NULL;
ALTER TABLE dashboard_widgets ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE dashboard_widgets ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE dashboard_widgets ADD COLUMN IF NOT EXISTS grid_w integer DEFAULT 1 NOT NULL;
ALTER TABLE dashboard_widgets ADD COLUMN IF NOT EXISTS grid_h integer DEFAULT 1 NOT NULL;
ALTER TABLE deleted_files ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('deleted_files_id_seq'::regclass) NOT NULL;
ALTER TABLE deleted_files ADD COLUMN IF NOT EXISTS entity_id integer;
ALTER TABLE deleted_files ADD COLUMN IF NOT EXISTS entity_name_json jsonb;
ALTER TABLE deleted_files ADD COLUMN IF NOT EXISTS record_id integer;
ALTER TABLE deleted_files ADD COLUMN IF NOT EXISTS field_key text;
ALTER TABLE deleted_files ADD COLUMN IF NOT EXISTS field_name_json jsonb;
ALTER TABLE deleted_files ADD COLUMN IF NOT EXISTS file_name text;
ALTER TABLE deleted_files ADD COLUMN IF NOT EXISTS file_path text;
ALTER TABLE deleted_files ADD COLUMN IF NOT EXISTS file_size integer;
ALTER TABLE deleted_files ADD COLUMN IF NOT EXISTS content_type text;
ALTER TABLE deleted_files ADD COLUMN IF NOT EXISTS reason text;
ALTER TABLE deleted_files ADD COLUMN IF NOT EXISTS deleted_by integer;
ALTER TABLE deleted_files ADD COLUMN IF NOT EXISTS deleted_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('entities_id_seq'::regclass) NOT NULL;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS entity_key text;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS name_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS description_json jsonb DEFAULT '{}'::jsonb;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS icon text DEFAULT 'table'::text NOT NULL;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS page_id integer;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0 NOT NULL;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true NOT NULL;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS default_sort_json jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS pivot_enabled boolean DEFAULT false NOT NULL;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS default_filter_json jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS default_pivot_json jsonb;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS allow_no_status boolean DEFAULT true NOT NULL;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS default_page_size integer;
ALTER TABLE entity_automation_runs ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('entity_automation_runs_id_seq'::regclass) NOT NULL;
ALTER TABLE entity_automation_runs ADD COLUMN IF NOT EXISTS automation_id integer;
ALTER TABLE entity_automation_runs ADD COLUMN IF NOT EXISTS entity_id integer;
ALTER TABLE entity_automation_runs ADD COLUMN IF NOT EXISTS record_id integer;
ALTER TABLE entity_automation_runs ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE entity_automation_runs ADD COLUMN IF NOT EXISTS trigger_name text;
ALTER TABLE entity_automation_runs ADD COLUMN IF NOT EXISTS detail_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE entity_automation_runs ADD COLUMN IF NOT EXISTS dedupe_key text;
ALTER TABLE entity_automation_runs ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE entity_automations ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('entity_automations_id_seq'::regclass) NOT NULL;
ALTER TABLE entity_automations ADD COLUMN IF NOT EXISTS entity_id integer;
ALTER TABLE entity_automations ADD COLUMN IF NOT EXISTS name_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE entity_automations ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true NOT NULL;
ALTER TABLE entity_automations ADD COLUMN IF NOT EXISTS trigger_json jsonb;
ALTER TABLE entity_automations ADD COLUMN IF NOT EXISTS conditions_json jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE entity_automations ADD COLUMN IF NOT EXISTS actions_json jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE entity_automations ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0 NOT NULL;
ALTER TABLE entity_automations ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE entity_automations ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE entity_automations ADD COLUMN IF NOT EXISTS condition_conjunction text DEFAULT 'and'::text NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('entity_fields_id_seq'::regclass) NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS entity_id integer;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS field_key text;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS name_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS description_json jsonb DEFAULT '{}'::jsonb;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS field_type text DEFAULT 'text'::text NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS is_required boolean DEFAULT false NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS default_value text;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS options_json jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0 NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS permissions_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS is_filterable boolean DEFAULT false NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS show_in_table boolean DEFAULT true NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS file_config_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS user_config_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS format_rules_json jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS formula_config_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS show_column_total boolean DEFAULT false NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS total_fill_color text;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS total_text_color text;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS dependency_config_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS is_pinned boolean DEFAULT false NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS is_key boolean DEFAULT false NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS lock_after_create boolean DEFAULT false NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS relation_config_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS pivot_enabled boolean DEFAULT false NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS column_group_id integer;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS validation_rules_json jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS wrap_text boolean DEFAULT false NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS default_to_today boolean DEFAULT false NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS percent_config_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE entity_fields ADD COLUMN IF NOT EXISTS format_inherit_json jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE entity_records ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('entity_records_id_seq'::regclass) NOT NULL;
ALTER TABLE entity_records ADD COLUMN IF NOT EXISTS entity_id integer;
ALTER TABLE entity_records ADD COLUMN IF NOT EXISTS values_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE entity_records ADD COLUMN IF NOT EXISTS status_id integer;
ALTER TABLE entity_records ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE entity_records ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE entity_records ADD COLUMN IF NOT EXISTS archived_at timestamp with time zone;
ALTER TABLE entity_records ADD COLUMN IF NOT EXISTS status_changed_at timestamp with time zone;
ALTER TABLE entity_records ADD COLUMN IF NOT EXISTS archive_exempt boolean DEFAULT false NOT NULL;
ALTER TABLE entity_records ADD COLUMN IF NOT EXISTS version integer DEFAULT 1 NOT NULL;
ALTER TABLE entity_statuses ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('entity_statuses_id_seq'::regclass) NOT NULL;
ALTER TABLE entity_statuses ADD COLUMN IF NOT EXISTS entity_id integer;
ALTER TABLE entity_statuses ADD COLUMN IF NOT EXISTS status_key text;
ALTER TABLE entity_statuses ADD COLUMN IF NOT EXISTS name_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE entity_statuses ADD COLUMN IF NOT EXISTS color text DEFAULT '#6b7280'::text NOT NULL;
ALTER TABLE entity_statuses ADD COLUMN IF NOT EXISTS is_default boolean DEFAULT false NOT NULL;
ALTER TABLE entity_statuses ADD COLUMN IF NOT EXISTS is_final boolean DEFAULT false NOT NULL;
ALTER TABLE entity_statuses ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0 NOT NULL;
ALTER TABLE entity_statuses ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true NOT NULL;
ALTER TABLE entity_statuses ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE entity_statuses ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE entity_statuses ADD COLUMN IF NOT EXISTS is_archive_trigger boolean DEFAULT false NOT NULL;
ALTER TABLE entity_statuses ADD COLUMN IF NOT EXISTS archive_after_days integer DEFAULT 0 NOT NULL;
ALTER TABLE entity_transitions ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('entity_transitions_id_seq'::regclass) NOT NULL;
ALTER TABLE entity_transitions ADD COLUMN IF NOT EXISTS entity_id integer;
ALTER TABLE entity_transitions ADD COLUMN IF NOT EXISTS from_status_id integer;
ALTER TABLE entity_transitions ADD COLUMN IF NOT EXISTS to_status_id integer;
ALTER TABLE entity_transitions ADD COLUMN IF NOT EXISTS name_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE entity_transitions ADD COLUMN IF NOT EXISTS allowed_role_ids jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE entity_transitions ADD COLUMN IF NOT EXISTS required_field_keys jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE entity_transitions ADD COLUMN IF NOT EXISTS actions_json jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE entity_transitions ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0 NOT NULL;
ALTER TABLE entity_transitions ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE entity_transitions ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE google_drive_connection ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('google_drive_connection_id_seq'::regclass) NOT NULL;
ALTER TABLE google_drive_connection ADD COLUMN IF NOT EXISTS key_mode text DEFAULT 'builtin'::text NOT NULL;
ALTER TABLE google_drive_connection ADD COLUMN IF NOT EXISTS own_client_id text;
ALTER TABLE google_drive_connection ADD COLUMN IF NOT EXISTS own_client_secret_enc text;
ALTER TABLE google_drive_connection ADD COLUMN IF NOT EXISTS refresh_token_enc text;
ALTER TABLE google_drive_connection ADD COLUMN IF NOT EXISTS account_email text;
ALTER TABLE google_drive_connection ADD COLUMN IF NOT EXISTS folder_id text;
ALTER TABLE google_drive_connection ADD COLUMN IF NOT EXISTS folder_name text;
ALTER TABLE google_drive_connection ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE google_drive_connection ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE google_drive_folders ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('google_drive_folders_id_seq'::regclass) NOT NULL;
ALTER TABLE google_drive_folders ADD COLUMN IF NOT EXISTS drive_folder_id text;
ALTER TABLE google_drive_folders ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE google_drive_folders ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0 NOT NULL;
ALTER TABLE google_drive_folders ADD COLUMN IF NOT EXISTS is_default boolean DEFAULT false NOT NULL;
ALTER TABLE google_drive_folders ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE google_drive_folders ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE google_drive_folders ADD COLUMN IF NOT EXISTS parent_id integer;
ALTER TABLE google_drive_folders ADD COLUMN IF NOT EXISTS name_template_json jsonb;
ALTER TABLE guest_links ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('guest_links_id_seq'::regclass) NOT NULL;
ALTER TABLE guest_links ADD COLUMN IF NOT EXISTS user_id integer;
ALTER TABLE guest_links ADD COLUMN IF NOT EXISTS token_hash text;
ALTER TABLE guest_links ADD COLUMN IF NOT EXISTS label text;
ALTER TABLE guest_links ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;
ALTER TABLE guest_links ADD COLUMN IF NOT EXISTS revoked_at timestamp with time zone;
ALTER TABLE guest_links ADD COLUMN IF NOT EXISTS last_used_at timestamp with time zone;
ALTER TABLE guest_links ADD COLUMN IF NOT EXISTS created_by integer;
ALTER TABLE guest_links ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE local_folders ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('local_folders_id_seq'::regclass) NOT NULL;
ALTER TABLE local_folders ADD COLUMN IF NOT EXISTS storage_dir text;
ALTER TABLE local_folders ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE local_folders ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0 NOT NULL;
ALTER TABLE local_folders ADD COLUMN IF NOT EXISTS is_default boolean DEFAULT false NOT NULL;
ALTER TABLE local_folders ADD COLUMN IF NOT EXISTS parent_id integer;
ALTER TABLE local_folders ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE local_folders ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE login_history ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('login_history_id_seq'::regclass) NOT NULL;
ALTER TABLE login_history ADD COLUMN IF NOT EXISTS user_id integer;
ALTER TABLE login_history ADD COLUMN IF NOT EXISTS ip_address text DEFAULT ''::text NOT NULL;
ALTER TABLE login_history ADD COLUMN IF NOT EXISTS user_agent text;
ALTER TABLE login_history ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE modules ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('modules_id_seq'::regclass) NOT NULL;
ALTER TABLE modules ADD COLUMN IF NOT EXISTS module_key text;
ALTER TABLE modules ADD COLUMN IF NOT EXISTS name_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE modules ADD COLUMN IF NOT EXISTS version text DEFAULT '1.0.0'::text NOT NULL;
ALTER TABLE modules ADD COLUMN IF NOT EXISTS is_enabled boolean DEFAULT false NOT NULL;
ALTER TABLE modules ADD COLUMN IF NOT EXISTS settings_json jsonb DEFAULT '{}'::jsonb;
ALTER TABLE modules ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE modules ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('page_fields_id_seq'::regclass) NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS page_id integer;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS field_key text;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS name_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS description_json jsonb DEFAULT '{}'::jsonb;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS field_type text DEFAULT 'text'::text NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS is_required boolean DEFAULT false NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS default_value text;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS options_json jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS format_rules_json jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS show_in_table boolean DEFAULT true NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0 NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS formula_config_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS show_column_total boolean DEFAULT false NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS total_fill_color text;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS total_text_color text;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS relation_config_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS permissions_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS is_pinned boolean DEFAULT false NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS is_filterable boolean DEFAULT false NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS pivot_enabled boolean DEFAULT false NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS column_group_id integer;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS percent_config_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE page_fields ADD COLUMN IF NOT EXISTS wrap_text boolean DEFAULT false NOT NULL;
ALTER TABLE page_record_values ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('page_record_values_id_seq'::regclass) NOT NULL;
ALTER TABLE page_record_values ADD COLUMN IF NOT EXISTS page_id integer;
ALTER TABLE page_record_values ADD COLUMN IF NOT EXISTS record_id integer;
ALTER TABLE page_record_values ADD COLUMN IF NOT EXISTS values_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE page_record_values ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE page_record_values ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE page_record_values ADD COLUMN IF NOT EXISTS version integer DEFAULT 1 NOT NULL;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('pages_id_seq'::regclass) NOT NULL;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS name_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS description_json jsonb DEFAULT '{}'::jsonb;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS icon text DEFAULT 'file'::text NOT NULL;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS parent_page_id integer;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0 NOT NULL;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true NOT NULL;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS path text;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS mirror_entity_id integer;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS mirror_field_keys_json jsonb;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS is_dashboard boolean DEFAULT false NOT NULL;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS widgets_collapsed_default boolean DEFAULT false NOT NULL;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS mirror_field_labels_json jsonb;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS is_pivot boolean DEFAULT false NOT NULL;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS pivot_entity_id integer;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS pivot_config_json jsonb;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS mirror_column_order_json jsonb;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS column_groups_json jsonb;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS default_quick_filter_json jsonb;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS group_by_field_key text;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS mirror_pinned_json jsonb;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS group_default_expanded boolean DEFAULT false NOT NULL;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS filters_collapsed_default boolean DEFAULT false NOT NULL;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS hide_status_column boolean DEFAULT false NOT NULL;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS default_sort_json jsonb;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS default_page_size integer;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS disable_create boolean DEFAULT false NOT NULL;
ALTER TABLE record_links ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('record_links_id_seq'::regclass) NOT NULL;
ALTER TABLE record_links ADD COLUMN IF NOT EXISTS relation_id integer;
ALTER TABLE record_links ADD COLUMN IF NOT EXISTS relation_type text;
ALTER TABLE record_links ADD COLUMN IF NOT EXISTS source_record_id integer;
ALTER TABLE record_links ADD COLUMN IF NOT EXISTS target_record_id integer;
ALTER TABLE record_links ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE relations ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('relations_id_seq'::regclass) NOT NULL;
ALTER TABLE relations ADD COLUMN IF NOT EXISTS source_entity_id integer;
ALTER TABLE relations ADD COLUMN IF NOT EXISTS target_entity_id integer;
ALTER TABLE relations ADD COLUMN IF NOT EXISTS relation_key text;
ALTER TABLE relations ADD COLUMN IF NOT EXISTS relation_type text DEFAULT 'one_to_many'::text NOT NULL;
ALTER TABLE relations ADD COLUMN IF NOT EXISTS name_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE relations ADD COLUMN IF NOT EXISTS inverse_name_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE relations ADD COLUMN IF NOT EXISTS settings_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE relations ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE relations ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('roles_id_seq'::regclass) NOT NULL;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS name_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS description_json jsonb DEFAULT '{}'::jsonb;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS permissions_json jsonb DEFAULT '{"admin": {"pages": false, "roles": false, "users": false, "events": false, "modules": false, "entities": false, "settings": false, "dataImport": false, "automations": false, "googleDrive": false, "columnGroups": false, "translations": false, "customFilters": false}, "pageIds": [], "records": {}, "superAdmin": false}'::jsonb NOT NULL;
ALTER TABLE system_events ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('system_events_id_seq'::regclass) NOT NULL;
ALTER TABLE system_events ADD COLUMN IF NOT EXISTS event_name text;
ALTER TABLE system_events ADD COLUMN IF NOT EXISTS entity_id integer;
ALTER TABLE system_events ADD COLUMN IF NOT EXISTS record_id integer;
ALTER TABLE system_events ADD COLUMN IF NOT EXISTS payload_json jsonb DEFAULT '{}'::jsonb;
ALTER TABLE system_events ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE translations ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('translations_id_seq'::regclass) NOT NULL;
ALTER TABLE translations ADD COLUMN IF NOT EXISTS translation_key text;
ALTER TABLE translations ADD COLUMN IF NOT EXISTS translations_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE translations ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE translations ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE user_roles ADD COLUMN IF NOT EXISTS user_id integer;
ALTER TABLE user_roles ADD COLUMN IF NOT EXISTS role_id integer;
ALTER TABLE user_roles ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('users_id_seq'::regclass) NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS role_id integer;
ALTER TABLE users ADD COLUMN IF NOT EXISTS language text DEFAULT 'ru'::text NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS direction text DEFAULT 'ltr'::text NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS start_page_id integer;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE views ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('views_id_seq'::regclass) NOT NULL;
ALTER TABLE views ADD COLUMN IF NOT EXISTS entity_id integer;
ALTER TABLE views ADD COLUMN IF NOT EXISTS view_key text;
ALTER TABLE views ADD COLUMN IF NOT EXISTS name_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE views ADD COLUMN IF NOT EXISTS config_json jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE views ADD COLUMN IF NOT EXISTS is_default boolean DEFAULT false NOT NULL;
ALTER TABLE views ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0 NOT NULL;
ALTER TABLE views ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true NOT NULL;
ALTER TABLE views ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE views ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE views ADD COLUMN IF NOT EXISTS visible_role_ids_json jsonb;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='app_settings_pkey') THEN ALTER TABLE app_settings ADD CONSTRAINT app_settings_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='audit_log_pkey') THEN ALTER TABLE audit_log ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='column_groups_pkey') THEN ALTER TABLE column_groups ADD CONSTRAINT column_groups_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='custom_filters_pkey') THEN ALTER TABLE custom_filters ADD CONSTRAINT custom_filters_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='dashboard_widgets_pkey') THEN ALTER TABLE dashboard_widgets ADD CONSTRAINT dashboard_widgets_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='deleted_files_pkey') THEN ALTER TABLE deleted_files ADD CONSTRAINT deleted_files_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entities_entity_key_unique') THEN ALTER TABLE entities ADD CONSTRAINT entities_entity_key_unique UNIQUE (entity_key); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entities_pkey') THEN ALTER TABLE entities ADD CONSTRAINT entities_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entity_automation_runs_pkey') THEN ALTER TABLE entity_automation_runs ADD CONSTRAINT entity_automation_runs_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entity_automations_pkey') THEN ALTER TABLE entity_automations ADD CONSTRAINT entity_automations_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entity_field_key_unique') THEN ALTER TABLE entity_fields ADD CONSTRAINT entity_field_key_unique UNIQUE (entity_id, field_key); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entity_fields_pkey') THEN ALTER TABLE entity_fields ADD CONSTRAINT entity_fields_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entity_records_pkey') THEN ALTER TABLE entity_records ADD CONSTRAINT entity_records_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entity_status_key_unique') THEN ALTER TABLE entity_statuses ADD CONSTRAINT entity_status_key_unique UNIQUE (entity_id, status_key); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entity_statuses_pkey') THEN ALTER TABLE entity_statuses ADD CONSTRAINT entity_statuses_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entity_transitions_pkey') THEN ALTER TABLE entity_transitions ADD CONSTRAINT entity_transitions_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='google_drive_connection_pkey') THEN ALTER TABLE google_drive_connection ADD CONSTRAINT google_drive_connection_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='google_drive_folders_drive_folder_id_unique') THEN ALTER TABLE google_drive_folders ADD CONSTRAINT google_drive_folders_drive_folder_id_unique UNIQUE (drive_folder_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='google_drive_folders_pkey') THEN ALTER TABLE google_drive_folders ADD CONSTRAINT google_drive_folders_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='guest_links_pkey') THEN ALTER TABLE guest_links ADD CONSTRAINT guest_links_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='guest_links_token_hash_unique') THEN ALTER TABLE guest_links ADD CONSTRAINT guest_links_token_hash_unique UNIQUE (token_hash); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='local_folders_pkey') THEN ALTER TABLE local_folders ADD CONSTRAINT local_folders_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='local_folders_storage_dir_unique') THEN ALTER TABLE local_folders ADD CONSTRAINT local_folders_storage_dir_unique UNIQUE (storage_dir); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='login_history_pkey') THEN ALTER TABLE login_history ADD CONSTRAINT login_history_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='modules_module_key_unique') THEN ALTER TABLE modules ADD CONSTRAINT modules_module_key_unique UNIQUE (module_key); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='modules_pkey') THEN ALTER TABLE modules ADD CONSTRAINT modules_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='page_field_key_unique') THEN ALTER TABLE page_fields ADD CONSTRAINT page_field_key_unique UNIQUE (page_id, field_key); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='page_fields_pkey') THEN ALTER TABLE page_fields ADD CONSTRAINT page_fields_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='page_record_value_unique') THEN ALTER TABLE page_record_values ADD CONSTRAINT page_record_value_unique UNIQUE (page_id, record_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='page_record_values_pkey') THEN ALTER TABLE page_record_values ADD CONSTRAINT page_record_values_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='pages_pkey') THEN ALTER TABLE pages ADD CONSTRAINT pages_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='record_link_unique') THEN ALTER TABLE record_links ADD CONSTRAINT record_link_unique UNIQUE (relation_id, source_record_id, target_record_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='record_links_pkey') THEN ALTER TABLE record_links ADD CONSTRAINT record_links_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='relation_source_key_unique') THEN ALTER TABLE relations ADD CONSTRAINT relation_source_key_unique UNIQUE (source_entity_id, relation_key); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='relations_pkey') THEN ALTER TABLE relations ADD CONSTRAINT relations_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='roles_pkey') THEN ALTER TABLE roles ADD CONSTRAINT roles_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='system_events_pkey') THEN ALTER TABLE system_events ADD CONSTRAINT system_events_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='translations_pkey') THEN ALTER TABLE translations ADD CONSTRAINT translations_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='translations_translation_key_unique') THEN ALTER TABLE translations ADD CONSTRAINT translations_translation_key_unique UNIQUE (translation_key); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_roles_user_id_role_id_pk') THEN ALTER TABLE user_roles ADD CONSTRAINT user_roles_user_id_role_id_pk PRIMARY KEY (user_id, role_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='users_email_unique') THEN ALTER TABLE users ADD CONSTRAINT users_email_unique UNIQUE (email); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='users_pkey') THEN ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='view_entity_key_unique') THEN ALTER TABLE views ADD CONSTRAINT view_entity_key_unique UNIQUE (entity_id, view_key); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='views_pkey') THEN ALTER TABLE views ADD CONSTRAINT views_pkey PRIMARY KEY (id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='custom_filters_entity_id_entities_id_fk') THEN ALTER TABLE custom_filters ADD CONSTRAINT custom_filters_entity_id_entities_id_fk FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='dashboard_widgets_page_id_pages_id_fk') THEN ALTER TABLE dashboard_widgets ADD CONSTRAINT dashboard_widgets_page_id_pages_id_fk FOREIGN KEY (page_id) REFERENCES pages(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entities_page_id_pages_id_fk') THEN ALTER TABLE entities ADD CONSTRAINT entities_page_id_pages_id_fk FOREIGN KEY (page_id) REFERENCES pages(id) ON DELETE SET NULL; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entity_automation_runs_automation_id_entity_automations_id_fk') THEN ALTER TABLE entity_automation_runs ADD CONSTRAINT entity_automation_runs_automation_id_entity_automations_id_fk FOREIGN KEY (automation_id) REFERENCES entity_automations(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entity_automations_entity_id_entities_id_fk') THEN ALTER TABLE entity_automations ADD CONSTRAINT entity_automations_entity_id_entities_id_fk FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entity_fields_entity_id_entities_id_fk') THEN ALTER TABLE entity_fields ADD CONSTRAINT entity_fields_entity_id_entities_id_fk FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entity_records_entity_id_entities_id_fk') THEN ALTER TABLE entity_records ADD CONSTRAINT entity_records_entity_id_entities_id_fk FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entity_records_status_id_entity_statuses_id_fk') THEN ALTER TABLE entity_records ADD CONSTRAINT entity_records_status_id_entity_statuses_id_fk FOREIGN KEY (status_id) REFERENCES entity_statuses(id) ON DELETE SET NULL; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entity_statuses_entity_id_entities_id_fk') THEN ALTER TABLE entity_statuses ADD CONSTRAINT entity_statuses_entity_id_entities_id_fk FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entity_transitions_entity_id_entities_id_fk') THEN ALTER TABLE entity_transitions ADD CONSTRAINT entity_transitions_entity_id_entities_id_fk FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entity_transitions_from_status_id_entity_statuses_id_fk') THEN ALTER TABLE entity_transitions ADD CONSTRAINT entity_transitions_from_status_id_entity_statuses_id_fk FOREIGN KEY (from_status_id) REFERENCES entity_statuses(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='entity_transitions_to_status_id_entity_statuses_id_fk') THEN ALTER TABLE entity_transitions ADD CONSTRAINT entity_transitions_to_status_id_entity_statuses_id_fk FOREIGN KEY (to_status_id) REFERENCES entity_statuses(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='google_drive_folders_parent_id_google_drive_folders_id_fk') THEN ALTER TABLE google_drive_folders ADD CONSTRAINT google_drive_folders_parent_id_google_drive_folders_id_fk FOREIGN KEY (parent_id) REFERENCES google_drive_folders(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='guest_links_user_id_users_id_fk') THEN ALTER TABLE guest_links ADD CONSTRAINT guest_links_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='local_folders_parent_id_local_folders_id_fk') THEN ALTER TABLE local_folders ADD CONSTRAINT local_folders_parent_id_local_folders_id_fk FOREIGN KEY (parent_id) REFERENCES local_folders(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='page_fields_page_id_pages_id_fk') THEN ALTER TABLE page_fields ADD CONSTRAINT page_fields_page_id_pages_id_fk FOREIGN KEY (page_id) REFERENCES pages(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='page_record_values_page_id_pages_id_fk') THEN ALTER TABLE page_record_values ADD CONSTRAINT page_record_values_page_id_pages_id_fk FOREIGN KEY (page_id) REFERENCES pages(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='page_record_values_record_id_entity_records_id_fk') THEN ALTER TABLE page_record_values ADD CONSTRAINT page_record_values_record_id_entity_records_id_fk FOREIGN KEY (record_id) REFERENCES entity_records(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='record_links_relation_id_relations_id_fk') THEN ALTER TABLE record_links ADD CONSTRAINT record_links_relation_id_relations_id_fk FOREIGN KEY (relation_id) REFERENCES relations(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='record_links_source_record_id_entity_records_id_fk') THEN ALTER TABLE record_links ADD CONSTRAINT record_links_source_record_id_entity_records_id_fk FOREIGN KEY (source_record_id) REFERENCES entity_records(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='record_links_target_record_id_entity_records_id_fk') THEN ALTER TABLE record_links ADD CONSTRAINT record_links_target_record_id_entity_records_id_fk FOREIGN KEY (target_record_id) REFERENCES entity_records(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='relations_source_entity_id_entities_id_fk') THEN ALTER TABLE relations ADD CONSTRAINT relations_source_entity_id_entities_id_fk FOREIGN KEY (source_entity_id) REFERENCES entities(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='relations_target_entity_id_entities_id_fk') THEN ALTER TABLE relations ADD CONSTRAINT relations_target_entity_id_entities_id_fk FOREIGN KEY (target_entity_id) REFERENCES entities(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_roles_role_id_roles_id_fk') THEN ALTER TABLE user_roles ADD CONSTRAINT user_roles_role_id_roles_id_fk FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_roles_user_id_users_id_fk') THEN ALTER TABLE user_roles ADD CONSTRAINT user_roles_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='views_entity_id_entities_id_fk') THEN ALTER TABLE views ADD CONSTRAINT views_entity_id_entities_id_fk FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE CASCADE; END IF; END $$;
CREATE INDEX IF NOT EXISTS custom_filter_entity_idx ON public.custom_filters USING btree (entity_id);
CREATE INDEX IF NOT EXISTS entity_automation_entity_idx ON public.entity_automations USING btree (entity_id);
CREATE INDEX IF NOT EXISTS entity_automation_run_automation_idx ON public.entity_automation_runs USING btree (automation_id);
CREATE UNIQUE INDEX IF NOT EXISTS entity_automation_run_dedupe_unique ON public.entity_automation_runs USING btree (automation_id, record_id, dedupe_key) WHERE (dedupe_key IS NOT NULL);
CREATE INDEX IF NOT EXISTS entity_automation_run_entity_idx ON public.entity_automation_runs USING btree (entity_id);
CREATE UNIQUE INDEX IF NOT EXISTS entity_status_one_default ON public.entity_statuses USING btree (entity_id) WHERE (is_default = true);
CREATE INDEX IF NOT EXISTS entity_transition_entity_idx ON public.entity_transitions USING btree (entity_id);
CREATE INDEX IF NOT EXISTS entity_transition_from_idx ON public.entity_transitions USING btree (from_status_id);
CREATE UNIQUE INDEX IF NOT EXISTS entity_transition_specific_unique ON public.entity_transitions USING btree (entity_id, from_status_id, to_status_id) WHERE (from_status_id IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS entity_transition_wildcard_unique ON public.entity_transitions USING btree (entity_id, to_status_id) WHERE (from_status_id IS NULL);
CREATE UNIQUE INDEX IF NOT EXISTS local_folders_single_default_idx ON public.local_folders USING btree (is_default) WHERE (is_default = true);
CREATE UNIQUE INDEX IF NOT EXISTS record_link_source_one ON public.record_links USING btree (relation_id, source_record_id) WHERE (relation_type = ANY (ARRAY['one_to_one'::text, 'many_to_one'::text]));
CREATE UNIQUE INDEX IF NOT EXISTS record_link_target_one ON public.record_links USING btree (relation_id, target_record_id) WHERE (relation_type = ANY (ARRAY['one_to_one'::text, 'one_to_many'::text]));
CREATE UNIQUE INDEX IF NOT EXISTS view_one_default ON public.views USING btree (entity_id) WHERE (is_default = true);
CREATE OR REPLACE FUNCTION public.bump_collaboration_version() RETURNS trigger AS $$
BEGIN
  IF NEW.version = OLD.version THEN NEW.version := OLD.version + 1; END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS entity_records_version_bump ON public.entity_records;
CREATE TRIGGER entity_records_version_bump BEFORE UPDATE ON public.entity_records FOR EACH ROW EXECUTE FUNCTION public.bump_collaboration_version();
DROP TRIGGER IF EXISTS page_record_values_version_bump ON public.page_record_values;
CREATE TRIGGER page_record_values_version_bump BEFORE UPDATE ON public.page_record_values FOR EACH ROW EXECUTE FUNCTION public.bump_collaboration_version();
COMMIT;
